name: PHP CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, mysqli

    - name: Install MySQL server
      run: sudo apt-get install -y mysql-server

    - name: Start MySQL service
      run: sudo service mysql start

    - name: Create .env file
      run: |
        cp .env.example .env
        sed -i 's/^DB_HOST=.*/DB_HOST=localhost/' .env
        sed -i 's/^DB_DATABASE=.*/DB_DATABASE=phpapp/' .env
        sed -i 's/^DB_USERNAME=.*/DB_USERNAME=root/' .env
        sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=/' .env

    - name: Enable PHP error logging
      run: |
        echo 'log_errors = On' >> /etc/php/8.3/cli/php.ini
        echo 'display_errors = On' >> /etc/php/8.3/cli/php.ini
        echo 'error_log = /tmp/php-errors.log' >> /etc/php/8.3/cli/php.ini

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Start PHP server
      run: php -S localhost:8000 -t www -d error_log=/tmp/php-errors.log &

    - name: Run curl request on main page
      run: |
        curl -i http://localhost:8000 || true

    - name: Display PHP error log if 500
      if: failure()
      run: cat /tmp/php-errors.log || echo "No errors in PHP log"
