name: PHP CI/CD

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: database
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, pdo_mysql
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Install Apache
      run: |
        sudo apt-get update
        sudo apt-get install apache2 -y
        sudo a2enmod rewrite
        sudo service apache2 start

    - name: Create .env file
      run: |
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_USER=root" >> .env
        echo "DB_PASS=" >> .env
        echo "DB_NAME=database" >> .env
        echo "DB_PORT=${{ job.services.mysql.ports[3306] }}" >> .env
        echo "DB_PREFIX=prefix_" >> .env

    - name: Configure Apache
      run: |
        sudo cp -r ./* /var/www/html/
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 755 /var/www/html
        echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/info.php

    - name: Check Apache status
      run: sudo systemctl status apache2

    - name: List /var/www/html contents
      run: ls -la /var/www/html

    - name: Check Apache error log
      run: sudo cat /var/log/apache2/error.log

    - name: Test if site is accessible
      run: |
        echo "Trying to access http://localhost"
        response=$(curl -v http://localhost 2>&1)
        echo "Full curl response:"
        echo "$response"
        if [[ $response == *"PHP Version"* ]]; then
          echo "Site is accessible and PHP is working"
        else
          echo "Site is not accessible or PHP is not working"
          echo "Trying to access http://localhost/info.php"
          response=$(curl -v http://localhost/info.php 2>&1)
          echo "Full curl response for info.php:"
          echo "$response"
          exit 1
        fi

    - name: PHP Version
      run: php -v

    - name: PHP Modules
      run: php -m
